// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iulpiuoukmibwvbrpmxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1bHBpdW91a21pYnd2YnJwbXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5ODU1MzIsImV4cCI6MjA5ODU2MTUzMn0.IsWWzWvQnWBeapDyoU11kS6cVN0C-ZYywmyUK5z836I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});